# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=250)),
                ('body', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=64)),
                ('video', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_name', models.CharField(max_length=64)),
                ('page_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.PageContent')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='issues',
            field=models.ManyToManyField(to='main.Issue'),
        ),
    ]
