# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='page_content',
        ),
        migrations.AddField(
            model_name='issue',
            name='body',
            field=models.CharField(default='body', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.CharField(default='image', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='summary',
            field=models.CharField(default='summary', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='video',
            field=models.CharField(default='video', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
