# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_issue_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='scope',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='video',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
